/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package smart_grid;

import java.util.Random;

/**
 *
 * @author riazr
 */
public class dashboard extends javax.swing.JFrame {

    /**
     * Creates new form dashboard
     */
    public dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        var_TA_00 = new javax.swing.JLabel();
        var_TA_01 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        var_TA_10 = new javax.swing.JLabel();
        var_TA_11 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SmartGrid: A project for Game Theory Course");
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(46, 46, 71));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(46, 46, 71));
        jPanel3.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("A project for GameTheory");

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("SMARTGRID");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel2.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jLabel22.setBackground(new java.awt.Color(46, 46, 71));
        jLabel22.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smart_grid/logo-UNIPD-white.png"))); // NOI18N
        jLabel22.setLabelFor(jLabel22);
        jLabel22.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel2))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, java.awt.BorderLayout.NORTH);

        jPanel4.setBackground(new java.awt.Color(46, 46, 71));
        jPanel4.setPreferredSize(new java.awt.Dimension(249, 250));

        jButton1.setBackground(new java.awt.Color(46, 46, 71));
        jButton1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Start");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Syed Riaz Raza");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Syed Fahad Hassan");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel3)
                        .addGap(37, 37, 37)
                        .addComponent(jLabel4)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 413, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addContainerGap())
        );

        jPanel1.add(jPanel4, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.WEST);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextArea1);

        jTabbedPane1.addTab("Scenerio explained by description", jScrollPane1);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smart_grid/1605pg_25.jpg"))); // NOI18N

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPanel6.setLayout(new java.awt.GridLayout(3, 3, 15, 10));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("#");
        jPanel6.add(jLabel6);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("Allocation 0");
        jPanel6.add(jLabel7);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("Allocation 1");
        jPanel6.add(jLabel8);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setText("Timeslot 0");
        jPanel6.add(jLabel9);

        var_TA_00.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        var_TA_00.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        var_TA_00.setText("0 , 0");
        jPanel6.add(var_TA_00);

        var_TA_01.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        var_TA_01.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        var_TA_01.setText("0 , 0");
        jPanel6.add(var_TA_01);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel12.setText("Timeslot 1");
        jPanel6.add(jLabel12);

        var_TA_10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        var_TA_10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        var_TA_10.setText("0 , 0");
        jPanel6.add(var_TA_10);

        var_TA_11.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        var_TA_11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        var_TA_11.setText("0 , 0");
        jPanel6.add(var_TA_11);

        jLabel15.setText("Matrix Table:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(111, 111, 111))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel5)))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Scenerio Visualized", jPanel5);

        jPanel2.add(jTabbedPane1, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        // we have two time slots, t1 = 1
	// t2 = 2
        int[] timeSlots = new int[2];
        timeSlots[0] = 1;
        timeSlots[1] = 2;

        Random rand = new Random();

        // allocation to user
        int[] allocation = new int[2];
        allocation[0] = rand.nextInt(100) + 1;
        allocation[1] = rand.nextInt(100) + 1;

        // solar energy generation
        int[] solarEnergy = new int[2];
        solarEnergy[0] = rand.nextInt(100) + 1;
        solarEnergy[1] = rand.nextInt(100) + 1;

        // utility
        int energyDiff = 0;
        int batteryCharge = 10;
        int energyFromBattery = 0;
        int moneyLost = 0;	
        // for each of the time slot, calculate the utility
        // utility is expressed as solar - alloc
        for (int i=0; i<timeSlots.length; i++) {
            for (int j=0; j<allocation.length; j++) {
                jTextArea1.append("\n--TimeSlot: "+i+". Allocation: "+j+"--\n");
                        energyDiff = solarEnergy[j]- allocation[j];
                        jTextArea1.append("Energy difference obtained: "+energyDiff+"\n");
                        
                        // see if the energy diff obtained is greater than
                        // or less than zero
                        
                        // SCenerio#1
                        if (energyDiff > 0) {
                                // solar energy is more
                                // if solar energy is more
                                // charge the battery
                                // we SHOULD optimize this to add the charging
                                // discharging rate
                                jTextArea1.append("Energy difference is > 0. Charging battery upto: "+energyDiff+"\n");
                                batteryCharge = energyDiff;

                        }
                        
                        // SCenerio#2
                        else if (energyDiff < 0){
                               jTextArea1.append("Energy difference is < 0. Checking battery charge.\n");
                                // solar energy is being generated less
                                // check the battery
                                if (batteryCharge > 0) {
                                        // energy can be obtained from battery
                                        jTextArea1.append("Battery charge is > 0. Discharging from battery.\n");
                                        energyFromBattery = batteryCharge - Math.abs(energyDiff);

                                        // check how much energy is needed
                                        // from battery
                                        if (energyFromBattery > 0) {
                                                jTextArea1.append("We have enough battery to support us.\n");
                                                // awesome, battery saved us
                                                batteryCharge = batteryCharge - energyFromBattery;
                                        } else if (energyFromBattery < 0) {
                                                // we need to get some energy
                                                // from the provider
                                                // for which we need to pay depending on the
                                                // time slot
                                                jTextArea1.append("Our battery will not support us. We need to get energy from the utility provider.\n");
                                                if (i==0) {
                                                        // first time slot
                                                        moneyLost = Math.abs(energyFromBattery) * 2;
                                                        jTextArea1.append("Since it is the first time slot, we pay €2 for every kW. We end up paying: "+moneyLost +"\n");
                                                } else {
                                                        // second time slot
                                                        moneyLost = Math.abs(energyFromBattery) * 4;
                                                        jTextArea1.append("Since it is the second time slot, we pay €4 for every kW. We end up paying: "+moneyLost+"\n");
                                                } 
                                        }
                                } else {
                                        // we had exactly the same
                                        // then see if it is time slot 2 and
                                        // charge the battery
                                        if (i==1) {
                                                // charge the battery
                                                batteryCharge = batteryCharge + 17;
                                                moneyLost = 17 * 2;
                                                jTextArea1.append("Charging battery since we have used up energy from battery. Money lost: "+moneyLost+"\n");
                                        }
                                }
                        } 
                        
                        // SCenerio#3
                        else {
                                // solar and alloc cancel out
                                // we are happy
                                // but if it is off peak hours (t2)
                                // we could just charge the battery
                                if (i==1) {
                                        // charge the battery
                                        batteryCharge = batteryCharge + 17;
                                        moneyLost = 17*2;
                                        jTextArea1.append("We have exactly the same solar power as allocation. So, charging battery for a rainy day. Money lost: "+moneyLost+"\n");
                                }
                        }
                        if(i==0 && j==0)
                        {
                        var_TA_00.setText(energyDiff+" , "+moneyLost);
                        }
                        else if(i==0 && j==1)
                        {
                        var_TA_01.setText(energyDiff+" , "+moneyLost);
                        }
                        else if(i==1 && j==0)
                        {
                        var_TA_10.setText(energyDiff+" , "+moneyLost);
                        }
                        else if(i==1 && j==1)
                        {
                        var_TA_11.setText(energyDiff+" , "+moneyLost);
                        }
                           
                        
                        
                }
    }//GEN-LAST:event_jButton1ActionPerformed

    }            
                
    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel var_TA_00;
    private javax.swing.JLabel var_TA_01;
    private javax.swing.JLabel var_TA_10;
    private javax.swing.JLabel var_TA_11;
    // End of variables declaration//GEN-END:variables
}
